### PR TITLE
Cart management

### PR DESCRIPTION
**Pull request by kr-sarvesh**
please review my cart page

https://redecommerce.netlify.app/screens/cart/cart.html

### CODE REVIEW

**Review by arulk8 — COMMENTED** [review]
Font size can made little bigger.

**Review by arulk8 — COMMENTED** [review]
Looks good to go

**Review by Balakumar3018 — APPROVED** [review]
Good to go
Suggestion -  it would be better if you add search option in navigation bar

**Comment by SuchitaGhadge** [comment]
font looks little  fainted in my laptop. Don't know if its my laptop or you kept it that fainted intentionally.
Overall looks good. but if font is little bolder then it will be easy to read the text.
- you can add a buy now button below the total.

**Pull request merged**
